// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// M_regression_GS
Rcpp::List M_regression_GS(Rcpp::List& data, Rcpp::List& init, Rcpp::List& region_idx_cpp, Rcpp::List& kernel, arma::uword n_mcmc, bool display_progress);
RcppExport SEXP _RpkgBMA_M_regression_GS(SEXP dataSEXP, SEXP initSEXP, SEXP region_idx_cppSEXP, SEXP kernelSEXP, SEXP n_mcmcSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type region_idx_cpp(region_idx_cppSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(M_regression_GS(data, init, region_idx_cpp, kernel, n_mcmc, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// M_regression_region_block
Rcpp::List M_regression_region_block(arma::colvec& Y, arma::mat& M, arma::colvec& X, arma::mat& C, arma::uvec L_all, arma::uword num_region, Rcpp::List& region_idx, int n_mcmc, Rcpp::List& K, int stop_burnin, int unadjusted_langevin, double lambda, double& target_accept, Rcpp::List& init, int interval, double step, bool display_progress);
RcppExport SEXP _RpkgBMA_M_regression_region_block(SEXP YSEXP, SEXP MSEXP, SEXP XSEXP, SEXP CSEXP, SEXP L_allSEXP, SEXP num_regionSEXP, SEXP region_idxSEXP, SEXP n_mcmcSEXP, SEXP KSEXP, SEXP stop_burninSEXP, SEXP unadjusted_langevinSEXP, SEXP lambdaSEXP, SEXP target_acceptSEXP, SEXP initSEXP, SEXP intervalSEXP, SEXP stepSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type L_all(L_allSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type num_region(num_regionSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type region_idx(region_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type stop_burnin(stop_burninSEXP);
    Rcpp::traits::input_parameter< int >::type unadjusted_langevin(unadjusted_langevinSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double& >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(M_regression_region_block(Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, lambda, target_accept, init, interval, step, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// Y_regression_GS
Rcpp::List Y_regression_GS(Rcpp::List& data, Rcpp::List& init, Rcpp::List& region_idx_cpp, Rcpp::List& kernel, arma::uword n_mcmc, bool display_progress);
RcppExport SEXP _RpkgBMA_Y_regression_GS(SEXP dataSEXP, SEXP initSEXP, SEXP region_idx_cppSEXP, SEXP kernelSEXP, SEXP n_mcmcSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type region_idx_cpp(region_idx_cppSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(Y_regression_GS(data, init, region_idx_cpp, kernel, n_mcmc, display_progress));
    return rcpp_result_gen;
END_RCPP
}
// Y_regression_region_block_fast
Rcpp::List Y_regression_region_block_fast(arma::colvec& Y, arma::mat& M, arma::colvec& X, arma::mat& C, arma::uvec L_all, arma::uword num_region, Rcpp::List& region_idx, int n_mcmc, Rcpp::List& K, int stop_burnin, int unadjusted_langevin, int start_joint, double lambda, double target_accept, Rcpp::List& init, int interval, double step, bool display_progress);
RcppExport SEXP _RpkgBMA_Y_regression_region_block_fast(SEXP YSEXP, SEXP MSEXP, SEXP XSEXP, SEXP CSEXP, SEXP L_allSEXP, SEXP num_regionSEXP, SEXP region_idxSEXP, SEXP n_mcmcSEXP, SEXP KSEXP, SEXP stop_burninSEXP, SEXP unadjusted_langevinSEXP, SEXP start_jointSEXP, SEXP lambdaSEXP, SEXP target_acceptSEXP, SEXP initSEXP, SEXP intervalSEXP, SEXP stepSEXP, SEXP display_progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type L_all(L_allSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type num_region(num_regionSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type region_idx(region_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type stop_burnin(stop_burninSEXP);
    Rcpp::traits::input_parameter< int >::type unadjusted_langevin(unadjusted_langevinSEXP);
    Rcpp::traits::input_parameter< int >::type start_joint(start_jointSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type target_accept(target_acceptSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    rcpp_result_gen = Rcpp::wrap(Y_regression_region_block_fast(Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, start_joint, lambda, target_accept, init, interval, step, display_progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RpkgBMA_M_regression_GS", (DL_FUNC) &_RpkgBMA_M_regression_GS, 6},
    {"_RpkgBMA_M_regression_region_block", (DL_FUNC) &_RpkgBMA_M_regression_region_block, 17},
    {"_RpkgBMA_Y_regression_GS", (DL_FUNC) &_RpkgBMA_Y_regression_GS, 6},
    {"_RpkgBMA_Y_regression_region_block_fast", (DL_FUNC) &_RpkgBMA_Y_regression_region_block_fast, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_RpkgBMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
