# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initial values for image-on-scalar regression
#' 
#' @param data an R list object that contains the data
#' @param init R list object with initial values
#' @param region_idx_cpp a list of region idx for all regions starting from 0
#' @param kernel a list object containing Q and D
#' @param n_mcmc number of iterations
#' @param display_progress bool, 1 = display progress bar
M_regression_GS <- function(data, init, region_idx_cpp, kernel, n_mcmc, display_progress = TRUE) {
    .Call('_RpkgBMA_M_regression_GS', PACKAGE = 'RpkgBMA', data, init, region_idx_cpp, kernel, n_mcmc, display_progress)
}

M_regression_region_block <- function(Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, lambda, target_accept, init, interval, step, display_progress = TRUE) {
    .Call('_RpkgBMA_M_regression_region_block', PACKAGE = 'RpkgBMA', Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, lambda, target_accept, init, interval, step, display_progress)
}

Y_regression_GS <- function(data, init, region_idx_cpp, kernel, n_mcmc, display_progress = TRUE) {
    .Call('_RpkgBMA_Y_regression_GS', PACKAGE = 'RpkgBMA', data, init, region_idx_cpp, kernel, n_mcmc, display_progress)
}

Y_regression_region_block_fast <- function(Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, start_joint, lambda, target_accept, init, interval, step, display_progress = TRUE) {
    .Call('_RpkgBMA_Y_regression_region_block_fast', PACKAGE = 'RpkgBMA', Y, M, X, C, L_all, num_region, region_idx, n_mcmc, K, stop_burnin, unadjusted_langevin, start_joint, lambda, target_accept, init, interval, step, display_progress)
}

